/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 abstract.glb -T -K 
Files: abstract.glb [3.56MB] > C:\Personal + Work\tri-dimensional\public\Models\abstract-transformed.glb [327.85KB] (91%)
Author: cherkesgiller (https://sketchfab.com/cherkesgiller)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/abstract-design-5f61a7b5eaa64af093d7cd721c9ef5ad
Title: Abstract Design
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function AbstractOne(props) {
  const { nodes, materials } = useGLTF('/Models/abstract-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group>
        <mesh geometry={nodes.VoronoiDynoBake_Material_0.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} scale={1} />
      </group>
    </group>
  )
}

useGLTF.preload('/Models/abstract-transformed.glb')
