/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 abstract3.glb -T -K 
Files: abstract3.glb [1.9MB] > C:\Personal + Work\tri-dimensional\public\Models\abstract3-transformed.glb [77.52KB] (96%)
Author: riach (https://sketchfab.com/riach)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/abstract-rainbow-translucent-pendant-fd730e2886e748a0bd645d05fd96040d
Title: Abstract Rainbow Translucent Pendant
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function AbstractThree(props) {
  const { nodes, materials } = useGLTF('/Models/abstract3-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group>
        <mesh geometry={nodes['Hedra001_Material_#0_0'].geometry} material={materials.Material_0} position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.013} />
      </group>
    </group>
  )
}

useGLTF.preload('/Models/abstract3-transformed.glb')
