/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 abstract_ball.glb -T -K 
Files: abstract_ball.glb [1.32MB] > C:\Personal + Work\tri-dimensional\public\Models\abstract_ball-transformed.glb [181.04KB] (86%)
Author: Arigaia Sekuin (https://sketchfab.com/arigaia.sekuin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/abstract-ball-ffafe62053a745b8b2c8182e59239e79
Title: Abstract Ball
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function AbstractBall(props) {
  const { nodes, materials } = useGLTF('/Models/abstract_ball-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group>
        <mesh geometry={nodes.Icosphere002_0.geometry} material={materials['ballz2.002']} rotation={[-1.49, 1.315, 0.904]} scale={0.6} />
        <mesh geometry={nodes.Icosphere003_0.geometry} material={materials['Lightballz.002']} rotation={[-1.49, 1.315, 0.904]} scale={0.6} />
        <mesh geometry={nodes.Cube002_0.geometry} material={materials['Wireframy.002']} rotation={[2.161, 0.868, -3.138]} scale={0.6} />
        <mesh geometry={nodes.Cube003_0.geometry} material={materials['Ballz.002']} rotation={[-2.139, 0.997, 1.709]} scale={0.6} />
      </group>
    </group>
  )
}

useGLTF.preload('/Models/abstract_ball-transformed.glb')
