/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 abstract2.glb -T -K 
Files: abstract2.glb [278.68KB] > C:\Personal + Work\tri-dimensional\public\Models\abstract2-transformed.glb [30.22KB] (89%)
Author: ijosephpinta (https://sketchfab.com/ijosephpinta)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/abstract-6573b214ddb042419252089e6528c239
Title: Abstract
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function AbstractTwo(props) {
  const { nodes, materials } = useGLTF('/Models/abstract2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group>
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material.002']} position={[0, 0, 0]} rotation={[0, 0, 1.478]} scale={0.3}/>
      </group>
    </group>
  )
}

useGLTF.preload('/Models/abstract2-transformed.glb')
